version: '3.1'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "54325:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
